Задача 1

Подгрузите файл train_vector.csv с помощью функции np.loadtxt. Назовите подгруженный массив my_array. Убедитесь, что подгруженный массив имеет тип np.ndarray

In [2]:
import numpy as np

In [7]:
my_array = np.loadtxt("Numpy(практика)/train_vector.csv", delimiter = ',', skiprows = 1, usecols = (0,1,2,7,8,10))
type(my_array)

numpy.ndarray

Задача 2
Возьмите функцию из предыдущих домашних заданий, которая считает сумму всех элементов массива. Примените ее к my_array.

In [8]:
def q_sum (my_array):
    s = 0
    for q in my_array:
        s = s + q
    return print(s)
q_sum (my_array)

[3.97386000e+05 3.42000000e+02 2.05700000e+03 4.66000000e+02
 3.40000000e+02 2.86939493e+04]


Задача 3
Напишите функцию, которая считает среднее значение всех элементов массива. Примените ее к подгруженному массиву my_array.

In [12]:
def avrg (my_array):
    return  my_array.mean()
avrg(my_array)

80.30021498316499

Задача 4
Напишите функцию, которая ищет минимальный элемент массива. Примените ее к подгруженному массиву my_array

In [13]:
def minVal (my_array):
    return  my_array.min()
minVal(my_array)

0.0

Задача 5
Подгрузите файл iris.csv с помощью встроенной функции np.loadtxt. Назовите его my_2d_array. Напиишите функцию, которая считает сумму элементов массива по столбцам.

In [16]:
my_2d_array = np.loadtxt("Numpy(практика)/iris.csv", delimiter = ',', skiprows = 1, usecols = (0,1,2,3))
def sumColumn (my_2d_array):
    return  np.sum(my_2d_array, axis = 0)
sumColumn(my_2d_array)

array([876.5, 458.6, 563.7, 179.9])

Задача 6
транспонируйте my_2d_array
выполните матричное умножение my_2d_array на my_2d_array.T
выполните матричное умножение my_2d_array.T на my_2d_array

In [17]:
my_2d_array.T

array([[5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
        4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
        5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
        5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
        6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
        6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
        6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
        6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
        6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
        7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
        7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
        6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9],
       [3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
        3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       

In [18]:
np.matmul(my_2d_array, my_2d_array.T)

array([[40.26, 37.49, 37.03, ..., 51.33, 51.54, 48.09],
       [37.49, 35.01, 34.49, ..., 48.53, 48.6 , 45.41],
       [37.03, 34.49, 34.06, ..., 47.31, 47.5 , 44.32],
       ...,
       [51.33, 48.53, 47.31, ..., 82.29, 83.18, 77.47],
       [51.54, 48.6 , 47.5 , ..., 83.18, 84.45, 78.46],
       [48.09, 45.41, 44.32, ..., 77.47, 78.46, 73.06]])

In [19]:
np.matmul(my_2d_array.T,my_2d_array)

array([[5223.85, 2673.43, 3483.76, 1128.14],
       [2673.43, 1430.4 , 1674.3 ,  531.89],
       [3483.76, 1674.3 , 2582.71,  869.11],
       [1128.14,  531.89,  869.11,  302.33]])

Задание 7
Найдите в документации библиотеки numpy функцию, вычисляющую собственные числа матрицы.

Найдите собственные числа матриц (my_2d_array.T * my_2d_array) и (my_2d_array * my_2d_array.T) используя соответсующую функцию

In [20]:
import numpy.linalg as linalg

#my_2d_array.T my_2d_array
a = my_2d_array.T.dot(my_2d_array)
vals, vecs = linalg.eig(a)
vals

#my_2d_array my_2d_array.T
b = my_2d_array.dot(my_2d_array.T)
vals2, vecs2 = linalg.eig(b)
vals2

array([ 9.20830507e+03+0.00000000e+00j,  3.15454317e+02+0.00000000e+00j,
        1.19780429e+01+0.00000000e+00j,  3.55257020e+00+0.00000000e+00j,
       -7.63146244e-13+0.00000000e+00j,  7.04586513e-13+0.00000000e+00j,
       -5.94530106e-13+2.76116200e-13j, -5.94530106e-13-2.76116200e-13j,
        3.71064480e-13+3.95177857e-13j,  3.71064480e-13-3.95177857e-13j,
        4.56193784e-13+1.46890821e-13j,  4.56193784e-13-1.46890821e-13j,
        2.02162295e-13+4.23565237e-13j,  2.02162295e-13-4.23565237e-13j,
       -1.57660805e-13+3.93562628e-13j, -1.57660805e-13-3.93562628e-13j,
       -3.28758347e-13+2.16053635e-13j, -3.28758347e-13-2.16053635e-13j,
       -3.53893693e-14+3.78349584e-13j, -3.53893693e-14-3.78349584e-13j,
        3.28529981e-13+1.14568631e-13j,  3.28529981e-13-1.14568631e-13j,
       -3.55510433e-13+7.28964236e-14j, -3.55510433e-13-7.28964236e-14j,
        2.16637767e-13+2.39310084e-13j,  2.16637767e-13-2.39310084e-13j,
       -2.55570762e-13+1.79278825e-13j, -2.55570762