### Задача 1: Вычисления по цепочке

Напишите функцию, которая возвращает значение следующей математической функции в зависимости от переменной х, где x - одномерный вектор.

$f(x) = \frac{1}{2}x^2 arctg(x) + 5cos(2x) + e^{x} + \log{6x}$

Проверьте работу функции на заданном векторе


In [6]:
import numpy as np

In [13]:
x = np.array([4,7,9])
F =  0.5 * x**2 * np.arctan(x) + 5 * np.cos(2 * x) + np.exp(x) + np.log(6 * x)
print(F)


[  67.655245   1136.06254631 8169.51012894]


### Задача 2: Вычисления по цепочке

Напишите функцию, которая вычисляет значение следующей математической функции в зависимости от переменной х, где х - вектор

$F(x) = \frac{3}{4}AA^Tx + Bx + c$

In [15]:
np.random.seed(42)

A = np.random.randint(1, 10, size = (3, 3))
B = np.random.randint(1, 10, size = (3, 3))
c = np.random.randint(1, 10, size = (3))
x = np.random.randint(1, 10, size = (3))

F1 = 0.75 * A.dot(A.T).dot(x) + B.dot(x) + c
print(F1)

[1364.5  1113.25 1454.5 ]


### Задача 3: 

Дана разреженная матрица, преобразуйте ее в csr формат, посчитайте долю разреженности, т.е. содержания нулей

In [2]:
import numpy as np
from scipy.sparse import csr_matrix

In [9]:
np.random.seed(42)

A = np.eye(45)
A[1, :] = np.random.randint(0, 2, size = (45))

In [11]:
A

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 1., 1., 1.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [14]:
aA = csr_matrix(A)
print (aA)

Z = 1.0 - np.count_nonzero(A) / A.size
print (Z)

  (0, 0)	1.0
  (1, 1)	1.0
  (1, 5)	1.0
  (1, 9)	1.0
  (1, 14)	1.0
  (1, 16)	1.0
  (1, 17)	1.0
  (1, 18)	1.0
  (1, 20)	1.0
  (1, 22)	1.0
  (1, 23)	1.0
  (1, 24)	1.0
  (1, 25)	1.0
  (1, 26)	1.0
  (1, 27)	1.0
  (1, 28)	1.0
  (1, 29)	1.0
  (1, 32)	1.0
  (1, 33)	1.0
  (1, 34)	1.0
  (1, 36)	1.0
  (1, 42)	1.0
  (1, 43)	1.0
  (1, 44)	1.0
  (2, 2)	1.0
  :	:
  (20, 20)	1.0
  (21, 21)	1.0
  (22, 22)	1.0
  (23, 23)	1.0
  (24, 24)	1.0
  (25, 25)	1.0
  (26, 26)	1.0
  (27, 27)	1.0
  (28, 28)	1.0
  (29, 29)	1.0
  (30, 30)	1.0
  (31, 31)	1.0
  (32, 32)	1.0
  (33, 33)	1.0
  (34, 34)	1.0
  (35, 35)	1.0
  (36, 36)	1.0
  (37, 37)	1.0
  (38, 38)	1.0
  (39, 39)	1.0
  (40, 40)	1.0
  (41, 41)	1.0
  (42, 42)	1.0
  (43, 43)	1.0
  (44, 44)	1.0
0.9669135802469135


### Задача 4

Даны две разреженные матрицы, преобразуйте их в формат csr и посчитайте:

* сумму двух матриц
* матричное произведение двух матриц
* выведите на экран сумму и произведение, предварительно преобразовав их обратно в "плотный" формат (метод .todense)

In [2]:
import numpy as np
from scipy.sparse import csr_matrix

In [3]:
np.random.seed(42)

A = np.eye(40)
A[4, :] = np.random.randint(0, 2, size = (40))

B = np.eye(40)
B[36, :] = np.random.randint(0, 2, size = (40))
B[:, 5] = np.random.randint(0, 2, size = (40))


In [4]:
Ac = csr_matrix(A)
Bc = csr_matrix(B)



In [8]:
S = Ac + Bc
M = Ac.dot(Bc)

In [9]:
S.todense()

matrix([[2., 0., 0., ..., 0., 0., 0.],
        [0., 2., 0., ..., 0., 0., 0.],
        [0., 0., 2., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 2., 0., 0.],
        [0., 0., 0., ..., 0., 2., 0.],
        [0., 0., 0., ..., 0., 0., 2.]])

In [11]:
M.todense()

matrix([[1., 0., 0., ..., 0., 0., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 1., 0., 0.],
        [0., 0., 0., ..., 0., 1., 0.],
        [0., 0., 0., ..., 0., 0., 1.]])